name: release-deno-rust-library
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: macOS-latest
    steps:
      - name: Cross-Compile Rust
        uses: flowscripter/.github/actions/cross-compile-deno-rust-library@v1
        with:
          release: true
      - name: Release Deno and Rust
        uses: flowscripter/.github/actions/release-deno-rust-library@v1
        with:
          name: flowscripter_template_deno_rust_library
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
